<?php

/**
* CSS colors and style file including
*
* @package DatingPro
* @subpackage User Mode
**/

// MODIFIED BY RALF TO AVOID READING THE DATABASE
// OUTPUT GENERATED BY PHP TO AVOID LOADING THE SMARTY TEMPLATE ENGINE
// EXPIRES HEADER ADDED TO ENABLE CACHING

// SPEED OPTION BY RALF
define('USER_DEFINED_COLORS', false);

header('Content-type: text/css');

// when caching with expires is enabled, changes to the .css files can take up to 1 hour to be effective.
// or disable caching, load the page, and then enable caching again.
# header('Expires: '.gmdate('D, d M Y H:i:s', time() + 3600).' GMT');

include './include/config.php';
include './common.php';
include './include/functions_common.php';

if (USER_DEFINED_COLORS)
{
	if (isset($_GET['customised']) && $_GET['customised'] == 1 && isset($_GET['user_id']) && isset($config['use_pilot_module_organizer']) && $config['use_pilot_module_organizer'] == 1)
	{
		// overwrite default colors with userdefined colors
		$strSQL =
			'SELECT id, home_area_color, menu_back_1_color, menu_back_2_color,
					menu_back_3_color, menu_back_4_color, menu_font_1_color, menu_font_2_color,
					menu_font_3_color, menu_font_4_color, link_color, header_color, content_color,
					search_color, shoutbox_color, main_text_color,
					big_bg_color, bg_picture_path
			   FROM '.ORG_USER_LAYOUTS_TABLE.'
			  WHERE id_user="'.intval($_GET['user_id']).'"';
		$rs = $dbconn->Execute($strSQL);
		
		if (!empty($rs->fields[0]))
		{
			$row = $rs->GetRowAssoc(false);
			if ($row['home_area_color'] != '') {
				$color['home_menu'] = $row['home_area_color'];
			}
			if ($row['shoutbox_color'] != '') {
				$color['shoutbox_color'] = $row['shoutbox_color'];
			}
			if ($row['menu_back_1_color'] != '') {
				$color['menu_block_1'] = $row['menu_back_1_color'];
			}
			if ($row['menu_back_2_color'] != '') {
				$color['menu_block_2'] = $row['menu_back_2_color'];
			}
			if ($row['menu_back_3_color'] != '') {
				$color['menu_block_3'] = $row['menu_back_3_color'];
			}
			if ($row['menu_back_4_color'] != '') {
				$color['menu_block_4'] = $row['menu_back_4_color'];
			}
			if ($row['menu_font_1_color'] != '') {
				$color['menu_link_1'] = $row['menu_font_1_color'];
			}
			if ($row['menu_font_2_color'] != '') {
				$color['menu_link_2'] = $row['menu_font_2_color'];
			}
			if ($row['menu_font_3_color'] != '') {
				$color['menu_link_3'] = $row['menu_font_3_color'];
			}
			if ($row['menu_font_4_color'] != '') {
				$color['menu_link_4'] = $row['menu_font_4_color'];
			}
			if ($row['link_color'] != '') {
				$color['link'] = $row['link_color'];
			}
			if ($row['header_color'] != '') {
				$color['header'] = $row['header_color'];
			}
			if ($row['content_color'] != '') {
				$color['content'] = $row['content_color'];
			}
			if ($row['search_color'] != '') {
				$color['home_search'] = $row['search_color'];
			}
			if ($row['big_bg_color'] != '') {
				$color['bg_color'] = $row['big_bg_color'];
			}
			if ($row['main_text_color'] != '') {
				$color['main_text_color'] = $row['main_text_color'];
			}
			if ($row['bg_picture_path'] != '') {
				$settings = GetSiteSettings(array('photos_folder'));
				$color['bg_picture_path'] = $config['site_root'].$settings['photos_folder'].'/'.$row['bg_picture_path'];
			}
		}
	}
}
else
{
	// some config settings are hardcoded to avoid loading the database drivers and reading the settings table
	// $config['site_path'] is read from /include/config.xml
	// $config['index_theme_path'] is read from the settings table
	
	include $config['site_path'].$config['index_theme_path'].'/css/config_color.php';
}

$css_color = $color;

?>