<option style="background-color:black; color: white" value="black">{$color.black}</option>
<option style="background-color:maroon; color: white" value="maroon">{$color.maroon}</option>
<option style="background-color:brown; color: white" value="brown">{$color.brown}</option>
<option style="background-color:red; color: white" value="red">{$color.red}</option>
<option style="background-color:tomato; color: white" value="tomato">{$color.tomato}</option>
<option style="background-color:orange; color: white" value="orange">{$color.orange}</option>
<option style="background-color:gold; color: white" value="gold">{$color.gold}</option>
<option style="background-color:yellow; color: white" value="yellow">{$color.yellow}</option>
<option style="background-color:goldenrod; color: white" value="goldenrod">{$color.goldenrod}</option>
<option style="background-color:peru; color: white" value="peru">{$color.peru}</option>
<option style="background-color:olive; color: white" value="olive">{$color.olive}</option>
<option style="background-color:palegreen; color: white" value="palegreen">{$color.palegreen}</option>
<option style="background-color:lime; color: white" value="lime">{$color.lime}</option>
<option style="background-color:green; color: white" value="green">{$color.green}</option>
<option style="background-color:darkgreen; color: white" value="darkgreen">{$color.darkgreen}</option>
<option style="background-color:mediumseagreen; color: white" value="mediumseagreen">{$color.mediumseagreen}</option>
<option style="background-color:lightseagreen; color: white" value="lightseagreen">{$color.lightseagreen}</option>
<option style="background-color:teal; color: white" value="teal">{$color.teal}</option>
<option style="background-color:lightsteelblue; color: white" value="lightsteelblue">{$color.lightsteelblue}</option>
<option style="background-color:lightskyblue; color: white" value="lightskyblue">{$color.lightskyblue}</option>
<option style="background-color:mediumslateblue; color: white" value="mediumslateblue">{$color.mediumslateblue}</option>
<option style="background-color:cyan; color: black" value="cyan">{$color.cyan}</option>
<option style="background-color:blue; color: white" value="blue">{$color.blue}</option>
<option style="background-color:darkblue; color: white" value="darkblue">{$color.darkblue}</option>
<option style="background-color:indigo; color: white" value="indigo">{$color.indigo}</option>
<option style="background-color:violet; color: white" value="violet">{$color.violet}</option>
<option style="background-color:orchid; color: white" value="orchid">{$color.orchid}</option>
<option style="background-color:plum; color: white" value="plum">{$color.plum}</option>
<option style="background-color:thistle; color: white" value="thistle">{$color.thistle}</option>
<option style="background-color:pink; color: white" value="pink">{$color.pink}</option>
<option style="background-color:hotpink; color: white" value="hotpink">{$color.hotpink}</option>
<option style="background-color:lightsalmon; color: white" value="lightsalmon">{$color.lightsalmon}</option>
<option style="background-color:tan; color: white" value="tan">{$color.tan}</option>
<option style="background-color:wheat; color: black" value="wheat">{$color.wheat}</option>
<option style="background-color:oldlace; color: black" value="oldlace">{$color.oldlace}</option>
<option style="background-color:honeydew; color: black" value="honeydew">{$color.honeydew}</option>
<option style="background-color:aliceblue; color: black" value="aliceblue">{$color.aliceblue}</option>
<option style="background-color:white; color: black" value="white">{$color.white}</option>
