<?php
$GLOBALS['fc_config']['themes']['alpin'] = array (
	  'name' => 'Alpin',
	  'dialogBackgroundImage' => 'images/alpin.jpg',
	  'backgroundImage' => 'images/alpin.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x355178,
	  'bodyText' => 0xFFFFFD,
	  'borderColor' => 0xBECBDC,
	  'button' => 0x2C4E7C,
	  'buttonBorder' => 0x325380,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0x5A7CAA,
	  'closeButton' => 0x2C4E7C,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x325380,
	  'closeButtonPress' => 0x325380,
	  'controlsBackground' => -1,
	  'dialog' => 0x5A7CAA,
	  'dialogTitle' => 0x415b7e,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0x5A7CAA,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0x5A7CAA,
	  'publicLogBackground' => 0x5A7CAA,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0x5A7CAA,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0x5A7CAA,
	  'userListItem' => -1
);
?>