<?php
$GLOBALS['fc_config']['themes']['argent'] = array (
	  'name' => 'Argent',
	  'dialogBackgroundImage' => 'images/argent.jpg',
	  'backgroundImage' => 'images/argent.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x534F44,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xC7C4BF,
	  'button' => 0x4F493D,
	  'buttonBorder' => 0x564E43,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0x5A7CAA,
	  'closeButton' => 0x4F493D,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x564E43,
	  'closeButtonPress' => 0x4F493D,
	  'controlsBackground' => -1,
	  'dialog' => 0x726C60,
	  'dialogTitle' => 0x565247,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0x726C60,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0x726C60,
	  'publicLogBackground' => 0x726C60,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0x726C60,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0x726C60,
	  'userListItem' => -1
);
?>