<?php
$GLOBALS['fc_config']['themes']['purple'] = array (
	  'name' => 'Purple',
	  'dialogBackgroundImage' => 'images/purple.jpg',
	  'backgroundImage' => 'images/purple.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0xA31869,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xDEA0C5,
	  'button' => 0xA8126b,
	  'buttonBorder' => 0x6E0142,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0xA7116A,
	  'closeButton' => 0xA8126b,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x6E0142,
	  'closeButtonPress' => 0xA8126b,
	  'controlsBackground' => -1,
	  'dialog' => 0xA7116A,
	  'dialogTitle' => 0x800d50,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0xA7116A,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0xA7116A,
	  'publicLogBackground' => 0xA7116A,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0xA7116A,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0xA7116A,
	  'userListItem' => -1
);
?>