<?php
$GLOBALS['fc_config']['themes']['sandy'] = array (
	  'name' => 'Sandy',
	  'dialogBackgroundImage' => 'images/sandy.jpg',
	  'backgroundImage' => 'images/sandy.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x724C01,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xE2CB99,
	  'button' => 0x694700,
	  'buttonBorder' => 0x392701,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0xAB7201,
	  'closeButton' => 0x694700,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x392701,
	  'closeButtonPress' => 0x694700,
	  'controlsBackground' => -1,
	  'dialog' => 0xAB7201,
	  'dialogTitle' => 0x825500,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0xAB7201,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0xAB7201,
	  'publicLogBackground' => 0xAB7201,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0xAB7201,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0xAB7201,
	  'userListItem' => -1
);
?>