<?php
$GLOBALS['fc_config']['themes']['scarlet'] = array (
	  'name' => 'Scarlet',
	  'dialogBackgroundImage' => 'images/scarlet.jpg',
	  'backgroundImage' => 'images/scarlet.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0xA22425,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xE09C9D,
	  'button' => 0xB11C1E,
	  'buttonBorder' => 0xCB1919,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0x9F0A0C,
	  'closeButton' => 0xB11C1E,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0xCB1919,
	  'closeButtonPress' => 0xB11C1E,
	  'controlsBackground' => -1,
	  'dialog' => 0x9F0A0C,
	  'dialogTitle' => 0x790908,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0x9F0A0C,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0x9F0A0C,
	  'publicLogBackground' => 0x9F0A0C,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0x9F0A0C,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0x9F0A0C,
	  'userListItem' => -1
);
?>