<?php
$GLOBALS['fc_config']['themes']['spring_green'] = array (
	  'name' => 'Spring Green',
	  'dialogBackgroundImage' => 'images/spring_green.jpg',
	  'backgroundImage' => 'images/spring_green.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x2A6F1F,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xFFFFFF,
	  'button' => 0x1C6B10,
	  'buttonBorder' => 0x1D7511,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0x307F24,
	  'closeButton' => 0x1C6B10,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x1D7511,
	  'closeButtonPress' => 0x1C6B10,
	  'controlsBackground' => -1,
	  'dialog' => 0x307F24,
	  'dialogTitle' => 0x25631A,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0x307F24,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0x307F24,
	  'publicLogBackground' => 0x307F24,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0x307F24,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0x307F24,
	  'userListItem' => -1
);
?>