<?php
$GLOBALS['fc_config']['themes']['sunny_orange'] = array (
	  'name' => 'Sunny orange',
	  'dialogBackgroundImage' => 'images/sunny_orange.jpg',
	  'backgroundImage' => 'images/sunny_orange.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x953A01,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xF3BD99,
	  'button' => 0x8A3701,
	  'buttonBorder' => 0x4A1E01,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0xD85401,
	  'closeButton' => 0x8A3701,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x4A1E01,
	  'closeButtonPress' => 0x8A3701,
	  'controlsBackground' => -1,
	  'dialog' => 0xD85401,
	  'dialogTitle' => 0x9D3D00,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0xD85401,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0xD85401,
	  'publicLogBackground' => 0xD85401,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0xD85401,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0xD85401,
	  'userListItem' => -1
);
?>