<?php
$GLOBALS['fc_config']['themes']['ultramarine'] = array (
	  'name' => 'Ultramarine',
	  'dialogBackgroundImage' => 'images/ultramarine.jpg',
	  'backgroundImage' => 'images/ultramarine.jpg',
	  'showBackgroundImagesOnLogin' => true,
	  'showBackgroundImages' => true,
	  'uiAlpha' => 0,
	  'background' => 0x3C448D,
	  'bodyText' => 0xFFFFFF,
	  'borderColor' => 0xA9ADD2,
	  'button' => 0x394398,
	  'buttonBorder' => 0x16217B,
	  'buttonPress' => -1,
	  'buttonText' => 0xFFFFFF,
	  'check' => 0x252F84,
	  'closeButton' => 0x394398,
	  'closeButtonArrow' => 0xFFFFFF,
	  'closeButtonBorder' => 0x16217B,
	  'closeButtonPress' => 0x394398,
	  'controlsBackground' => -1,
	  'dialog' => 0x252F84,
	  'dialogTitle' => 0x1A2260,
	  'enterRoomNotify' => 0xFFFFFF,
	  'headline' => -1,
	  'inputBoxBackground' => 0x252F84,

	  'minimizeButton' => 0xFFFFFF,
	  'minimizeButtonBorder' => 0xFFFFFF,
	  'minimizeButtonPress' => 0xFFFFFF,

	  'privateLogBackground' => 0x252F84,
	  'publicLogBackground' => 0x252F84,
	  'recommendedUserColor' => 0xFFFFFF,
	  'roomBackground' => 0x252F84,
	  'roomText' => 0xFFFFFF,
	  'scrollBG' => -1,
	  'scrollBGPress' => -1,
	  'scrollBorder' => -1,
	  'scrollerBG' => -1,
	  'titleText' => 0xFFFFFF,
	  'userListBackground' => 0x252F84,
	  'userListItem' => -1
);
?>